# Nom de l'application
spring.application.name=StageTrack

# Base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/stagetrack_db
spring.datasource.username=postgres
spring.datasource.password=passer

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Port du serveur
server.port=8082